# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.0
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_version: 12.0
org_name: TAKOBI
org_slug: SirTakobi
rebel_module_groups: []
repo_description: Repository for course on Odoo tests
repo_name: Test Course
repo_slug: Test-Course
repo_website: https://github.com/SirTakobi/Test-Course
travis_apt_packages: []
travis_apt_sources: []

